include:
  - docker-compose.infra.yml

services:
  producer:
    build:
      args:
        - app_name=producer
    depends_on:
      - rabbitmq
    expose:
      - "8080"
    env_file: .env
    restart: on-failure

  consumer:
    build:
      args:
        - app_name=consumer
    depends_on:
      - rabbitmq
    env_file: .env
    restart: on-failure
