include:
  - docker-compose.infra.yaml

services:
  producer:
    build:
      args:
        - app_name=producer
    links:
      - rabbitmq
    expose:
      - "8080"
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
    restart: on-failure
    networks:
      - monorepo

  consumer:
    build:
      args:
        - app_name=consumer
    links:
      - rabbitmq
    env_file: .env
    environment:
      - AMQP_URI=amqp://guest:guest@rabbitmq:5672/
      - ETCD_URIS=etcd:2379
    restart: on-failure
    networks:
      - monorepo
