services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - monorepo

volumes:
  rabbitmq_data:

networks:
  monorepo:
