{{- if (.Values.producer.enabled) -}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.producer.name }}-config
  labels:
    app: {{ .Values.producer.name }}
    ctx: {{ .Chart.Name }}
data:
  APP_ENV: {{ .Values.env }}
  AMQP_URI: {{ .Values.global.amqp.uri }}
  QUEUE_TOPIC: {{ .Values.global.amqp.topic }}

{{- end }}
