
env: production
global:
  amqp:
    uri: amqp://guest:guest@rabbitmq.infra:5672/
    topic: monorepo

cleanup:
  enabled: false
  targets:
    queue: true
    database: true
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  retry:
    attempts: 3
    backoff: "5s"
  timeout: "30s"
  image:
    repository: effective-monorepo/cleanup-sidecar
    tag: build

consumer:
  enabled: true
  name: consumer
  tag: build
  replicas: 1
  amqp:
    topicDLQ: monorepo-dlq
  etcd:
    uris: etcd.infra:2379
    prefix: monorepo

producer:
  enabled: true
  name: producer
  tag: build
  replicas: 1

test:
  enabled: true
  name: test
  tag: build
  producerUri: http://producer:8080
