name: CI pipeline

on:
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "README.md"
      - "helm/**"
      - "tilt/**"
  push:
    branches:
      - "master"
  workflow_dispatch:
    inputs:
      image_tag:
        description: "Version tag"
        type: string
        default: ''
      build-all:
        description: "Build all services"
        default: "true"
        type: choice
        options:
        - "true"
        - "false"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      toBuild: ${{ steps.create-matrix.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create matrix
        id: create-matrix
        uses: bmcszk/monorepo-matrix@v1
        with:
          build-all: ${{ inputs.build-all }}
          map: |-
            pkg|go.mod|go.sum|Dockerfile -> consumer|producer
            services/consumer -> consumer
            services/producer -> producer

  test:
    needs: [ detect-changes ]
    if: needs.detect-changes.outputs.toBuild != '[]'
    runs-on:
      group: k8s-runner-group-cwp
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up path
        run: |
          mkdir -p $HOME/.local
          mkdir -p $HOME/.local/bin
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Set up tools
        run: |
          make install-all-deps

      - name: Run k8s cluster with tests
        run: |
          cp .env.dist .env
          make kind-up tilt-ci

      - name: Clean k8s cluster
        if: always()
        run: |
          (make kind-down) || true
